/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kai' at '7/3/19 12:23 AM' with Gradle 3.2.1
 *
 * @author kai, @date 7/3/19 12:23 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
